### ISSUE TITLE
Regarding security concern

### ISSUE THREAD

**Issue by subodh101** [anuragdhingra/transferwise-go#4]
Since we are adding two very important piece of information:

- Transferwise personal API token
- Gmail password

As I went through your code, it seems safe at the moment.

But the most important thing is right now the docker version is set to `latest`.

Is there any possibility of you doing a fraudulent activity with regards to my personal information with you pushing a new docker version image? Have you thought about this?

**Comment by anuragdhingra** [comment]
It is a self hostable solution so I don't have access to any of your containers or the credentials.
And, the runtime env variables(token and Gmail password) are externally injected into the binary before running it, so it's not stored/copied anywhere in the built docker image.
Also, if there's a new release it doesn't affect your deployment as long as you decide to not fetch the latest image again.

Sorry if I am missing your point but I don't see how any of it is a security concern?

**Comment by subodh101** [comment]
Thank you for your reply, I really like the idea of transferwisely.

My concern is simple, let's say you decide to fetch all the gmail_id and password Or API token. And Inject a small piece of code in your codebase to send it to you :)

How can you make the user believe that you can't do this even if it's intentionally?

**Comment by anuragdhingra** [comment]
Isn't that the case with all of the opensource libraries or packages you use? 

Just for example sake, you must have used [viper](https://github.com/spf13/viper), right? 
Pretty popular configuration package for go, so how do you know that it isn't secretly passing your production config somewhere? Simple, by reading the implementation in case of such concerns, coz it's all opensource. I hope you get the point.

Also, about the docker image on docker-hub, that's built using the same Dockerfile, for the ease of end-user. In case of any other kind of concern, you can feel free to build your own image using the Dockerfile.
Please, close the issue if it clarifies your concern?

**Comment by subodh101** [comment]
Yes, you are right that's a concern. I get that point.

Thing is, Viper has 13300 github stars so it is self-understood that we can trust on that product up to a certain extent. Here on transferwisely, we are directly injecting some too important piece of information.

If I had to docker build then I wouldn't open the issue. Is it possible to version control docker-hub with releases? So we don't need to go over the changes done in the code.

**Comment by anuragdhingra** [comment]
Releases are versioned. You can check it here for the latest release.

https://github.com/anuragdhingra/transferwisely/releases/tag/v1.1 commit [a594dad](https://github.com/anuragdhingra/transferwisely/commit/a594dadeddda1fdd83e7a0556af3e654eff8f48b) 

https://hub.docker.com/r/anuragdhingra/transferwisely/builds

Is this what you were looking for?

**Comment by subodh101** [comment]
Yes, I am looking for something similar. Thank you for pointing out to the builds. Builds are currently updating images built under `latest` tag.

Consider:
https://hub.docker.com/r/tensorflow/tensorflow/tags

Here you can see release candidate image tags but in your case, it's only one and that's `latest`. So, can that be version controlled?

**Comment by anuragdhingra** [comment]
Okay, I get your point. But you can verify the latest image builds by the release commit hash as pointed above.
Also, about maintaining older image versions along with the latest one, I'll do that. Thank you.

**Comment by anuragdhingra** [comment]
Closing it for now.
